version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: ./src/TaskManagement.Api/Dockerfile
    container_name: taskmanagement.api-container
    image: taskmanagement.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - MSSQL_SA_PASSWORD=Password1*
      - MSSQL_PID=Express
    ports:
      - "5000:8080"
    depends_on:
      - sqlserverdb
  sqlserverdb:
    container_name: database-container
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433"
