#https://app-taskmanagement-sandropucp-dev.azurewebsites.net/swagger/index.html
@HostAddress = http://localhost:5200

GET {{HostAddress}}/tasks

//Server=SqlServerDb,1433;Database=carvedrock;User=sa;Password=A&VeryComplex123Password;TrustServerCertificate=True