name: CI

on:
  push:
    branches: ["master"]

jobs:
  build_and_test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: dotnet publish
        run: dotnet publish ./src/TaskManagement.Api/TaskManagement.Api.csproj -c Release -o ./publish    

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-artifact
          path: publish/

  deploy_dev:
    name: Deploy Dev
    needs: build_and_test
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: dev
      artifact_name: dotnet-artifact
      resource_group_name: gr-taskmanagement-dev
      app_service_name: app-taskmanagement-dev
      app_service_slot_name: slot
    # Note: use GH Environment Secrets if using a Pro/Enterprise version of GH
    secrets: inherit