name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  build_and_test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: dotnet publish
        run: dotnet publish ./src/TaskManagement.Api/TaskManagement.Api.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-artifact
          path: publish/

      - name: Install EntityFrameworkCore Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef

      - name: Generate EF Core Migration Script
        # run: dotnet ef migrations script --idempotent --no-build --configuration Release --output publish/sql/sql-script.sql --context src/TaskManagement.Infrastructure/TaskManagement.Infrastructure.csproj --project src/TaskManagement.Infrastructure -s src/TaskManagement.Api
        run:
          dotnet ef migrations script --idempotent --no-build --configuration Release --output publish/sql/sql-script.sql --context TaskManagementDbContext --project src/TaskManagement.Infrastructure -s src/TaskManagement.Api 
          #dotnet ef migrations script --idempotent --no-build --configuration Release --output publish/sql/sql-script.sql --context TaskManagement.Infrastructure.Common.Persistence.TaskManagementContext --project src/TaskManagement.Infrastructure/TaskManagement.Infrastructure.csproj -s src/TaskManagement.Api 
          

      - uses: actions/upload-artifact@v4
        with:
          name: ddl-updates
          path: publish/sql/sql-script.sql

  deploy_dev:
    name: Deploy Dev
    needs: build_and_test
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: dev
      artifact_name: dotnet-artifact
      resource_group_name: gr-taskmanagement-dev
      app_service_name: app-taskmanagement-sandropucp-dev
      app_service_slot_name: slot
    # Note: use GH Environment Secrets if using a Pro/Enterprise version of GH
    secrets: inherit
