name: CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: dotnet publish
        run: dotnet publish src\TaskManagement.Api\TaskManagement.Api.csproj --configuration Release --output publish/
