name: CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      #   - name: dotnet test
      #     run: dotnet test --configuration Release --no-build

      - name: dotnet publish
        run: dotnet publish src/TaskManagement.Api/TaskManagement.Api.csproj --configuration Release -o artifacts
