name: PR Verify

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: dotnet build
        run: dotnet build --configuration Release

      # - name: dotnet test 1
      #   run: dotnet test --configuration Release --no-build

      - name: dotnet format
        run: dotnet format -v detailed --verify-no-changes
